### ISSUE TITLE
Tag the current vcrpy-cleaner

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/vcrpy-cleaner#25]
## Context

We have been using the latest commit for awhile with no issue. We should tag this as 1.0.0.

## Tasks

- [x] update the CHANGELOG for 1.0.0
- [x] add a tag for 1.0.0
- [x] add a release for 1.0.0

**Comment by mpitcel** [comment]
PR for first task at: https://github.com/techservicesillinois/vcrpy-cleaner/pull/26

**Comment by mpitcel** [comment]
@edthedev , as this is a public repository, do we also want a Release for `1.0.0` instead of only a Tag?

**Comment by edthedev** [comment]
@mpitcel Good point! Yes, let's also create a 'Release'.

**Comment by mpitcel** [comment]
Tag and Release are available at: https://github.com/techservicesillinois/vcrpy-cleaner/releases/tag/1.0.0

**Comment by edthedev** [comment]
Looks great!
